name: Build and Release

on:
   push:
      tags:
         - "*"

permissions:
   contents: write

jobs:
   build-and-release:
      name: Build and Release
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Set up Go
           uses: actions/setup-go@v5
           with:
              go-version: "1.25.x"
              cache: true

         - name: Build Binary
           run: |
              CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o usetup .

         - name: Create Release
           uses: softprops/action-gh-release@v2
           with:
              files: usetup
              generate_release_notes: true
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
